version: '3.7'

volumes:
  notification_api_db:
    name: notification_api_db_volume


services:
  notification-api:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - notification-api-db
    container_name: notification-api-container
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://notification-api:notification-api@notification-api-db:5432
      - RUBYOPT=-W:no-deprecated -W:no-experimental
      - BUNDLE_PATH=/home/deploy/app/.bundle
      - BUNDLE_APP_CONFIG=/home/deploy/app/.bundle
    volumes:
      - .:/home/deploy/app:delegated
    ports:
      - 3000:3000
  notification-api-db:
    image: postgres:12-alpine
    container_name: notification-api-db-container
    environment:
      POSTGRES_USER: notification-api
      POSTGRES_PASSWORD: notification-api
      POSTGRES_DB: production
    volumes:
      - notification_api_db:/var/lib/postgresql/data:delegated
